#!/usr/bin/env python3
"""Generate Android strings solely from maintained native English and draft translations.

Missing translations fall back to English. Drafts are not native-speaker reviewed.
--check validates placeholders, plural quantities and exact generated resource bytes.
"""
import re, sys
from pathlib import Path

android = Path(__file__).resolve().parent.parent
res = android / 'app/src/main/res'
HEADER = '<!-- Generated by scripts/generate-strings.py from maintained native inputs. -->'
OLD_HEADER = '<!-- Generated by scripts/import-legacy-strings.py'
expected = {}
stale = []
# Maintained locale code: (language tag, Android resource qualifier). Hebrew resources keep Android's legacy code.
LANGUAGES = {'no': ('nb', 'nb'), 'he': ('he', 'iw'), 'pt-br': ('pt-BR', 'pt-rBR'), 'vi-vn': ('vi', 'vi'), 'zh-cn': ('zh-CN', 'zh-rCN'), 'zh_Hant': ('zh-Hant', 'b+zh+Hant')}
# A language is offered in the system's per-app language list only when at least 70% of these strings have maintained translations.
OFFERED = 0.7
# Keep new errors and player preferences explicit in partial locales without counting English as translation.
FALLBACK_NAMES = {'pl_total_track', 'pl_chapter_track', 'pl_scale_elapsed', 'pl_lock', 'pl_unlock'}
PLACEHOLDER = re.compile(r'%\d\$[sd]')
# CLDR cardinal plural categories Android uses, by maintained locale code; English's one/other elsewhere.
PLURALS = {'ar': 'zero one two few many other', 'be': 'one few many other', 'cs': 'one few many other', 'fr': 'one many other',
           'es': 'one many other', 'it': 'one many other', 'ca': 'one many other', 'pt-br': 'one many other', 'he': 'one two other',
           'hr': 'one few other', 'ja': 'other', 'ko': 'other', 'lt': 'one few many other', 'lv': 'zero one other', 'pl': 'one few many other',
           'ro': 'one few other', 'ru': 'one few many other', 'sk': 'one few many other', 'sl': 'one two few other', 'uk': 'one few many other',
           'vi-vn': 'other', 'zh-cn': 'other', 'zh_Hant': 'other', 'fa': 'one other', 'hi': 'one other', 'gu': 'one other', 'bn': 'one other'}
drafts = android / 'app/src/main/strings/drafts'
check = '--check' in sys.argv

rows = []
for line in (android / 'app/src/main/strings/strings.tsv').read_text().splitlines():
    if line and not line.startswith('#'):
        name, text = line.split('\t')
        rows.append((name, text.replace('\\n', '\n')))

def escape(text):
    text = text.replace('\\', '\\\\').replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    text = text.replace("'", "\\'").replace('"', '\\"').replace('\n', '\\n')
    return '\\' + text if text[:1] in '@?' else text

def write(directory, strings):
    directory.mkdir(parents=True, exist_ok=True) if not check else None
    plurals = {}
    for name, text in strings:
        if ':' in name:
            plurals.setdefault(name.split(':')[0], []).append((name.split(':')[1], text))
    body = ''.join(f'    <string name="{name}">{escape(text)}</string>\n' for name, text in strings if ':' not in name)
    body += ''.join(f'    <plurals name="{name}">\n' + ''.join(f'        <item quantity="{quantity}">{escape(text)}</item>\n' for quantity, text in items) + '    </plurals>\n'
                    for name, items in plurals.items())
    save(directory / 'strings.xml', f'<?xml version="1.0" encoding="utf-8"?>\n{HEADER}\n<resources>\n{body}</resources>\n')

def save(path, content):
    expected[path] = content
    if check:
        if not path.exists() or path.read_text() != content:
            stale.append(str(path.relative_to(android)))
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

write(res / 'values', rows)
english = dict(rows)
order = {name.split(':')[0]: index for index, (name, _) in reversed(list(enumerate(rows)))}
groups = {name.split(':')[0] for name in english}
offered, report = ['en'], []

def drafted(code):
    path = drafts / f'{code}.tsv'
    if not path.exists():
        return {}
    quantities = set(PLURALS.get(code, 'one other').split())
    found = {}
    for number, line in enumerate(path.read_text().splitlines(), 1):
        if not line or line.startswith('#'):
            continue
        name, text = line.split('\t')
        text = text.replace('\\n', '\n')
        group, _, quantity = name.partition(':')
        source = english.get(name) or english.get(f'{group}:other') if quantity else english.get(name)
        problem = ('unknown name' if source is None or (quantity and quantity not in quantities) else
                   'placeholders differ' if set(PLACEHOLDER.findall(text)) - set(PLACEHOLDER.findall(source))
                   or (quantity in ('', 'other') and sorted(PLACEHOLDER.findall(text)) != sorted(PLACEHOLDER.findall(source))) else None)
        if problem or not text.strip():
            raise SystemExit(f'{path.name}:{number} {name}: {problem or "empty"}')
        found[name] = text
    for group in {name.split(':')[0] for name in found if ':' in name}:
        if {name.split(':')[1] for name in found if name.split(':')[0] == group} != quantities:
            raise SystemExit(f'{path.name} {group}: needs exactly the quantities {" ".join(sorted(quantities))}')
    return found

for path in sorted(drafts.glob('*.tsv')):
    code = path.stem
    tag, qualifier = LANGUAGES.get(code, (code, code))
    strings = list(drafted(code).items())
    covered = {name.split(':')[0] for name, _ in strings}
    report.append(f'{code} {len(covered)}/{len(groups)} maintained, {len(groups) - len(covered)} English fallback')
    if strings:
        missing = [(name, text) for name, text in rows
                   if (name.startswith('err_') or name in FALLBACK_NAMES) and name.split(':')[0] not in covered]
        strings += missing
        write(res / f'values-{qualifier}', sorted(strings, key=lambda item: order[item[0].split(':')[0]]))
        if len(covered) >= OFFERED * len(groups):
            offered.append(tag)
save(res / 'xml/locales_config.xml', '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/generate-strings.py. -->\n<locale-config xmlns:android="http://schemas.android.com/apk/res/android">\n' + ''.join(f'    <locale android:name="{tag}" />\n' for tag in offered) + '</locale-config>\n')
for old in res.glob('values*/strings.xml'):
    if old not in expected and (HEADER in old.read_text() or OLD_HEADER in old.read_text()):
        if check:
            stale.append(str(old.relative_to(android)))
        else:
            old.unlink()
            if not any(old.parent.iterdir()):
                old.parent.rmdir()
print(f'{len(groups)} strings and plurals')
print('; '.join(report))
print(f'Offered ({len(offered) - 1} besides English):', ' '.join(offered))
if stale:
    raise SystemExit('Regenerate stale resources: ' + ', '.join(stale))
