#!/usr/bin/env python3
"""Writes the app's string resources from app/src/main/strings/strings.tsv, carrying the legacy app's
own translations (repository /strings) for every string whose meaning the legacy app already has.
Strings without a legacy translation fall back to English. Run after editing the table."""
import json, re
from pathlib import Path

android = Path(__file__).resolve().parent.parent
legacy = android.parent / 'strings'
res = android / 'app/src/main/res'
# Android resource qualifiers for the legacy file names; Norwegian is Bokmål, Hebrew keeps its legacy code.
QUALIFIERS = {'no': 'nb', 'he': 'iw', 'pt-br': 'pt-rBR', 'vi-vn': 'vi', 'zh-cn': 'zh-rCN', 'zh_Hant': 'b+zh+Hant'}
TAGS = {'no': 'nb', 'pt-br': 'pt-BR', 'vi-vn': 'vi', 'zh-cn': 'zh-CN', 'zh_Hant': 'zh-Hant'}
# A language is offered in the system's per-app language list only when most of these strings are translated.
OFFERED = 0.8
PLACEHOLDER = re.compile(r'%\d\$s')

rows = [line.split('\t') for line in (android / 'app/src/main/strings/strings.tsv').read_text().splitlines() if line and not line.startswith('#')]

def escape(text):
    text = text.replace('\\', '\\\\').replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    text = text.replace("'", "\\'").replace('"', '\\"').replace('\n', '\\n')
    return '\\' + text if text[:1] in '@?' else text

def write(directory, strings):
    directory.mkdir(parents=True, exist_ok=True)
    body = ''.join(f'    <string name="{name}">{escape(text)}</string>\n' for name, text in strings)
    (directory / 'strings.xml').write_text('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/import-legacy-strings.py from app/src/main/strings/strings.tsv. -->\n<resources>\n' + body + '</resources>\n')

write(res / 'values', [(name, text) for name, _, text in rows])
mapped = [(name, key, text) for name, key, text in rows if key != '-']
offered, report = ['en'], []
for path in sorted(legacy.glob('*.json')):
    code = path.stem
    if code == 'en-us':
        continue
    translations = json.loads(path.read_text())
    strings = []
    for name, key, text in mapped:
        value = re.sub(r'<[^>]+>', '', translations.get(key) or '')
        value = re.sub(r'\{(\d)\}', lambda m: f'%{int(m.group(1)) + 1}$s', value)
        # "Read %1$s" names the format; a legacy "Read" without it is still the right action.
        if value and (sorted(PLACEHOLDER.findall(value)) == sorted(PLACEHOLDER.findall(text)) or not PLACEHOLDER.findall(value)):
            strings.append((name, value))
    report.append(f'{code} {len(strings)}/{len(mapped)}')
    if strings:
        write(res / f'values-{QUALIFIERS.get(code, code)}', strings)
        if len(strings) >= OFFERED * len(mapped):
            offered.append(TAGS.get(code, code))
(res / 'xml/locales_config.xml').write_text('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/import-legacy-strings.py. -->\n<locale-config xmlns:android="http://schemas.android.com/apk/res/android">\n' + ''.join(f'    <locale android:name="{tag}" />\n' for tag in offered) + '</locale-config>\n')
print(f'{len(rows)} strings, {len(mapped)} with a legacy equivalent')
print('; '.join(report))
print('Offered:', ' '.join(offered))
