#!/usr/bin/env python3
"""Writes the app's string resources from app/src/main/strings/strings.tsv, carrying the legacy app's
own translations (repository /strings) for every string whose meaning the legacy app already has.
Strings without a legacy translation fall back to English. Run after editing the table."""
import json, re, shutil
from pathlib import Path

android = Path(__file__).resolve().parent.parent
legacy = android.parent / 'strings'
res = android / 'app/src/main/res'
HEADER = '<!-- Generated by scripts/import-legacy-strings.py from app/src/main/strings/strings.tsv. -->'
# Legacy file name: (language tag, Android resource qualifier). Hebrew resources keep Android's legacy code.
LANGUAGES = {'no': ('nb', 'nb'), 'he': ('he', 'iw'), 'pt-br': ('pt-BR', 'pt-rBR'), 'vi-vn': ('vi', 'vi'), 'zh-cn': ('zh-CN', 'zh-rCN'), 'zh_Hant': ('zh-Hant', 'b+zh+Hant')}
# A language is offered in the system's per-app language list only when most of these strings are translated.
OFFERED = 0.8
PLACEHOLDER = re.compile(r'%\d\$s')

rows = []
for line in (android / 'app/src/main/strings/strings.tsv').read_text().splitlines():
    if line and not line.startswith('#'):
        name, key, text, *wrong = line.split('\t')
        rows.append((name, key, text, set(wrong[0].split()) if wrong else set()))

def escape(text):
    text = text.replace('\\', '\\\\').replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    text = text.replace("'", "\\'").replace('"', '\\"').replace('\n', '\\n')
    return '\\' + text if text[:1] in '@?' else text

def write(directory, strings):
    directory.mkdir(parents=True, exist_ok=True)
    body = ''.join(f'    <string name="{name}">{escape(text)}</string>\n' for name, text in strings)
    (directory / 'strings.xml').write_text(f'<?xml version="1.0" encoding="utf-8"?>\n{HEADER}\n<resources>\n{body}</resources>\n')

for old in res.glob('values-*/strings.xml'):
    if HEADER in old.read_text():
        shutil.rmtree(old.parent) if len(list(old.parent.iterdir())) == 1 else old.unlink()
write(res / 'values', [(name, text) for name, _, text, _ in rows])
mapped = [row for row in rows if row[1] != '-']
offered, report = ['en'], []
for path in sorted(legacy.glob('*.json')):
    code = path.stem
    if code == 'en-us':
        continue
    tag, qualifier = LANGUAGES.get(code, (code, code))
    translations = json.loads(path.read_text())
    strings = []
    for name, key, text, wrong in mapped:
        value = re.sub(r'<[^>]+>', '', translations.get(key) or '').strip()
        value = re.sub(r'\{(\d)\}', lambda m: f'%{int(m.group(1)) + 1}$s', value)
        if value and code not in wrong and sorted(PLACEHOLDER.findall(value)) == sorted(PLACEHOLDER.findall(text)):
            strings.append((name, value))
    report.append(f'{code} {len(strings)}/{len(mapped)}')
    if strings:
        write(res / f'values-{qualifier}', strings)
        if len(strings) >= OFFERED * len(mapped):
            offered.append(tag)
(res / 'xml/locales_config.xml').write_text('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/import-legacy-strings.py. -->\n<locale-config xmlns:android="http://schemas.android.com/apk/res/android">\n' + ''.join(f'    <locale android:name="{tag}" />\n' for tag in offered) + '</locale-config>\n')
print(f'{len(rows)} strings, {len(mapped)} with a legacy equivalent')
print('; '.join(report))
print(f'Offered ({len(offered) - 1} besides English):', ' '.join(offered))
